# Generated by Django 3.1.4 on 2021-09-07 11:20

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Назва')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Опис')),
                ('price', models.BigIntegerField(verbose_name='Ціна')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.category', verbose_name='Категорія')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=255, verbose_name='Телефон користувача')),
                ('email', models.CharField(max_length=255, verbose_name='Email користувача')),
                ('address', models.TextField(verbose_name='Адреса доставки')),
                ('is_completed', models.BooleanField(verbose_name='Прапорець “виконання”')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення замовлення')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.product', verbose_name='Товар')),
            ],
        ),
    ]
